version: 2

models:
  - name: stg_customers
    description: "Tabela de staging para clientes. Contém um cliente por linha, com tipos de dados corrigidos."
    columns:
      - name: customer_id
        description: "Chave primária da tabela de clientes."
        tests:
          - unique
          - not_null

      - name: customer_unique_id
        description: "ID único que identifica um cliente, mesmo que ele faça múltiplos pedidos com contatos diferentes."
        tests:
          - not_null

  - name: stg_orders
    description: "Tabela de staging para pedidos. Contém um pedido por linha, com timestamps corrigidos."
    columns:
      - name: order_id
        description: "Chave primária da tabela de pedidos."
        tests:
          - unique
          - not_null

      - name: customer_id
        description: "Chave estrangeira para a tabela de clientes (stg_customers)."
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id

      - name: order_status
        description: "Status do pedido (ex: delivered, shipped)."
        tests:
          - not_null
          - accepted_values:
              values: ['delivered', 'shipped', 'canceled', 'unavailable', 'invoiced', 'processing', 'created', 'approved']

  - name: stg_order_items
    description: "Tabela de staging para os itens de cada pedido. Granularidade: um item de produto por linha."
    columns:
      - name: order_id
        description: "Chave estrangeira para a tabela de pedidos (stg_orders)."
        tests:
          - not_null
          - relationships:
              to: ref('stg_orders')
              field: order_id

      - name: product_id
        description: "Chave estrangeira para a tabela de produtos (stg_products)."
        tests:
          - not_null
          - relationships:
              to: ref('stg_products')
              field: product_id

      - name: price
        description: "Preço do produto no item do pedido."
        tests:
          - not_null

  - name: stg_products
    description: "Tabela de staging para produtos. Contém um produto único por linha."
    columns:
      - name: product_id
        description: "Chave primária da tabela de produtos."
        tests:
          - unique
          - not_null

  - name: stg_order_payments
    description: "Tabela de staging para os pagamentos de cada pedido. Um pedido pode ter múltiplos pagamentos."
    columns:
      - name: order_id
        description: "Chave estrangeira para a tabela de pedidos (stg_orders)."
        tests:
          - not_null
          - relationships:
              to: ref('stg_orders')
              field: order_id

      - name: payment_value
        description: "Valor do pagamento."
        tests:
          - not_null

  - name: stg_sellers
    description: "Tabela de staging para os vendedores."
    columns:
      - name: seller_id
        description: "Chave primária da tabela de vendedores."
        tests:
          - unique
          - not_null

  - name: stg_product_category_translation
    description: "Tabela de tradução dos nomes das categorias de produtos para o inglês."
    columns:
      - name: product_category_name
        description: "Nome da categoria em português."
        tests:
          - unique
          - not_null